### ISSUE TITLE
The baseline example can include a small ann example for neural networks

### ISSUE THREAD

**Issue by kaushikCanada** [radiantearth/agrifieldnet_india_competition#1]
the baseline example has a random forest classifier. I am having difficulty putting them into a neural network. May there could be an example of a small ann for this data.

**Comment by Troublem1** [comment]
@kaushikCanada  as stated in the Readme

> The starter notebook focuses on a simple baseline model using Random Forests to walk you through the process of loading and structuring the data, training the model, and exporting the predictions to the sample CSV file.

Also the current preprocessed data in the notebook can be used for create a neural network model in the form x being band1 ,2 , 3 &4 while  y being crop_id.

preferrably you can contact the active zindi community working on the competition through the [discussion forum](https://zindi.africa/competitions/agrifieldnet-india-challenge/discussions)

**Comment by kaushikCanada** [comment]
Hi ,

Thank you so much for the information. I am trying to use the x, but how to
make like a balanced pixel thing and dataloader for pytorch. Thats where im
stuck.

Thanks,
Roy

**Comment by guidorice** [comment]
@kaushikCanada thanks for your interest in the AgriFieldNet India Challenge! To keep the competition fair, please feel free to raise this issue in the discussion forum over here: https://zindi.africa/competitions/agrifieldnet-india-challenge/discussions .
