### ISSUE TITLE
TypeError: download() got an unexpected keyword argument 'collection_filter'

### ISSUE THREAD

**Issue by nadhirhasan** [radiantearth/agrifieldnet_india_competition#2]
Any solutions?

**Comment by ilymak7** [comment]
I had the same issue, i deleted that argument, and then specified output_dir , you may need to unzip the files afterwards, good luck

**Comment by PowerChell** [comment]
hi @nadhirhasan and @ilymak7. Which version of `radiant_mlhub` are you each using? the `collection_filter` parameter is only available in v0.5.0 and later.

**Comment by nadhirhasan** [comment]
Thanks for the reply. I just reinstalled radiant_mlhub. Now it works fine.
